# Generated by Django 4.2.27 on 2026-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0090_analysisgroup_workspace_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnaseqoutlier',
            name='mean_corrected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rnaseqoutlier',
            name='norm_counts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
